#!/usr/bin/env php
<?php

use Illuminate\Foundation\Application;
use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

$vendor = __DIR__ . '/vendor/autoload.php';

if (!file_exists($vendor)) {
    fwrite(STDERR, "Dependencies are missing. Run 'composer install' in " . __DIR__ . "\n");
    exit(1);
}

require $vendor;

// Bootstrap Laravel and handle the command...
/** @var Application $app */
$app = require_once __DIR__.'/bootstrap/app.php';

$status = $app->handleCommand(new ArgvInput);

exit($status);
